// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum Anchor: Int {
  case topLeft = 0
  case topRight = 1
  case bottomLeft = 2
  case bottomRight = 3
  case center = 4
}

enum OutputFormat: Int {
  case jpeg = 0
  case png = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct _Cfg: Hashable {


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> _Cfg? {

    return _Cfg(
    )
  }
  func toList() -> [Any?] {
    return [
    ]
  }
  static func == (lhs: _Cfg, rhs: _Cfg) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ComposeImageRequest: Hashable {
  var baseImage: FlutterStandardTypedData
  var watermarkImage: FlutterStandardTypedData
  var anchor: Anchor
  var margin: Double
  var widthPercent: Double
  var opacity: Double
  var format: OutputFormat
  var quality: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ComposeImageRequest? {
    let baseImage = pigeonVar_list[0] as! FlutterStandardTypedData
    let watermarkImage = pigeonVar_list[1] as! FlutterStandardTypedData
    let anchor = pigeonVar_list[2] as! Anchor
    let margin = pigeonVar_list[3] as! Double
    let widthPercent = pigeonVar_list[4] as! Double
    let opacity = pigeonVar_list[5] as! Double
    let format = pigeonVar_list[6] as! OutputFormat
    let quality = pigeonVar_list[7] as! Double

    return ComposeImageRequest(
      baseImage: baseImage,
      watermarkImage: watermarkImage,
      anchor: anchor,
      margin: margin,
      widthPercent: widthPercent,
      opacity: opacity,
      format: format,
      quality: quality
    )
  }
  func toList() -> [Any?] {
    return [
      baseImage,
      watermarkImage,
      anchor,
      margin,
      widthPercent,
      opacity,
      format,
      quality,
    ]
  }
  static func == (lhs: ComposeImageRequest, rhs: ComposeImageRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ComposeImageResult: Hashable {
  var imageBytes: FlutterStandardTypedData
  var width: Int64
  var height: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ComposeImageResult? {
    let imageBytes = pigeonVar_list[0] as! FlutterStandardTypedData
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64

    return ComposeImageResult(
      imageBytes: imageBytes,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      imageBytes,
      width,
      height,
    ]
  }
  static func == (lhs: ComposeImageResult, rhs: ComposeImageResult) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return Anchor(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OutputFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return _Cfg.fromList(self.readValue() as! [Any?])
    case 132:
      return ComposeImageRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return ComposeImageResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? Anchor {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? OutputFormat {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? _Cfg {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? ComposeImageRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ComposeImageResult {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WatermarkApi {
  func composeImage(request: ComposeImageRequest, completion: @escaping (Result<ComposeImageResult, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WatermarkApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `WatermarkApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WatermarkApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let composeImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.watermark_kit.WatermarkApi.composeImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      composeImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ComposeImageRequest
        api.composeImage(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      composeImageChannel.setMessageHandler(nil)
    }
  }
}
